project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get root to: 'users#home'
  get 'comparisons/save_comparison/:choice/:record_1_id/:record_2_id', to: 'comparisons#save_comparison'
  post 'comparisons/save_form_params', to: 'comparisons#save_form_params'
  get '/comparisons/start_survey', to: 'comparisons#start_survey'
  get '/comparisons/how_many_pairs', to: 'comparisons#how_many_pairs'
  get '/comparisons/survey_analytics', to: 'comparisons#survey_analytics'
  resources :records 
  resources :users do 
    resources :comparisons
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project/app/models/comparison.rb
class Comparison < ApplicationRecord
  belongs_to :record_1, :class_name => 'Record'
  belongs_to :record_2, :class_name => 'Record'
  belongs_to :user
end

project/app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  before_action :set_comparison, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /comparisons
  # GET /comparisons.json
  def index
    @comparisons = Comparison.all
  end

# GET /comparisons/survey_size
def how_many_pairs

end

# GET /comparisons/survey_end 
# controller method for finishing survey 
def survey_analytics
  @pairs = Comparison.where(user_id: current_user.id)
  ids = []
  @scores_dict = {}
  @pairs.each do |pair|
    ids << String(pair.record_1.crime_id)
    ids << String(pair.record_2.crime_id)
  end 
  # get the scores with one api call
  params = {'record_ids' => ids}
  response = HTTParty.post('https://algowatch.herokuapp.com/scores', 
    :body => params.to_json,
    :headers => { 'Content-Type' => 'application/json' })
  @scores_dict = JSON.parse(response.body)
  @score_names = @scores_dict[String(@pairs[0].record_1.crime_id)].keys

end

def save_form_params
  @num_pairs = params[:num_pairs].to_i 
  if @num_pairs >= 1
    current_user.pairs_count =  0 
    current_user.survey_size = @num_pairs
    if current_user.save
        redirect_to action: "start_survey"
    else
      render 'users/home'
    end
  else 
    render 'how_many_pairs'
  end 
end

  def start_survey
    # get two records (that aren't the same) and create comparison object
    response_1 = JSON.parse(Net::HTTP.get_response('algowatch.herokuapp.com', '/random').body)
    response_1["crime_id"] = response_1.delete("id")
    @rec_cols = Record.column_names
    record_1_hash = response_1.select { |key,_| @rec_cols.include? key }
    @record_1 = Record.new(record_1_hash)
    @record_1.save
    response_2 = JSON.parse(Net::HTTP.get_response('algowatch.herokuapp.com', '/random').body)
    response_2["crime_id"] = response_2.delete("id")
    record_2_hash = response_2.select { |key,_| @rec_cols.include? key }
    @record_2 = Record.new(record_2_hash)
    @record_2.save

    # [deprecated] pull random records from db. Faster. 
    # random_index = 2.times.map {rand(Record.count)}
    # @records = Record.find(random_index)
    # @record_1 = @records[0]
    # @record_2 = @records[1]

  end
  
  # handle post request from survey page
  # save comparison data 
  # redirect
  def save_comparison 
    # save comparison
    @comparison = Comparison.new({user_id: current_user.id, record_1_id: params[:record_1_id], record_2_id: params[:record_2_id], choice: params[:choice]})
    current_user.pairs_count += 1
    current_user.save
    if @comparison.save
      if current_user.pairs_count >= current_user.survey_size
        redirect_to action: "survey_analytics"
      else
        redirect_to action: "start_survey"
      end 
    else
      render 'users/home'
    end

  end

  # GET /comparisons/1
  # GET /comparisons/1.json
  def show
  end

  # GET /comparisons/new
  def new
    @comparison = Comparison.new
  end

  # GET /comparisons/1/edit
  def edit
  end

  # POST /comparisons
  # POST /comparisons.json
  def create
    @comparison = Comparison.new(comparison_params)
    if @comparison.save
      redirect_to @comparison
    else
      render :new 
    end
  end

  # PATCH/PUT /comparisons/1
  # PATCH/PUT /comparisons/1.json
  def update
    if @comparison.update(comparison_params)
      redirect_to @comparison
    else
      render :edit 
    end
  end

  # DELETE /comparisons/1
  # DELETE /comparisons/1.json
  def destroy
    @comparison.destroy
    redirect_to comparisons_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comparison
      @comparison = Comparison.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comparison_params
      params.require(:comparison).permit(:user_id, :record_1_id, :record_2_id, :choice)
    end
end

project/app/helpers/comparisons_helper.rb
module ComparisonsHelper
end

project/app/views/comparisons/_form.html.erb
<%= form_with(model: comparison, local: true) do |form| %>
  <% if comparison.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comparison.errors.count, "error") %> prohibited this comparison from being saved:</h2>

      <ul>
        <% comparison.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :record_id %>
    <%= form.text_field :record_id %>
  </div>

  <div class="field">
    <%= form.label :record_id %>
    <%= form.text_field :record_id %>
  </div>

  <div class="field">
    <%= form.label :choice %>
    <%= form.number_field :choice %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/comparisons/edit.html.erb
<h1>Editing Comparison</h1>

<%= render 'form', comparison: @comparison %>

<%= link_to 'Show', @comparison %> |
<%= link_to 'Back', comparisons_path %>

project/app/views/comparisons/how_many_pairs.html.erb
<p>   
    How many comparisons would you like to make?
</p>
<%= form_with url:'save_form_params' do |form| %>  
    <%= form.text_field :num_pairs %>    
  <input type="submit" value="Start Survey" class="btn btn-primary">
<% end %>

project/app/views/comparisons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comparisons</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Record</th>
      <th>Record</th>
      <th>Choice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comparisons.each do |comparison| %>
      <tr>
        <td><%= comparison.user_id %></td>
        <td><%= comparison.record_id %></td>
        <td><%= comparison.record_id %></td>
        <td><%= comparison.choice %></td>
        <td><%= link_to 'Show', comparison %></td>
        <td><%= link_to 'Edit', edit_comparison_path(comparison) %></td>
        <td><%= link_to 'Destroy', comparison, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comparison', new_comparison_path %>

project/app/views/comparisons/new.html.erb
<h1>New Comparison</h1>

<%= render 'form', comparison: @comparison %>

<%= link_to 'Back', comparisons_path %>

project/app/views/comparisons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comparison.user_id %>
</p>

<p>
  <strong>Record:</strong>
  <%= @comparison.record_id %>
</p>

<p>
  <strong>Record:</strong>
  <%= @comparison.record_id %>
</p>

<p>
  <strong>Choice:</strong>
  <%= @comparison.choice %>
</p>

<%= link_to 'Edit', edit_comparison_path(@comparison) %> |
<%= link_to 'Back', comparisons_path %>

project/app/views/comparisons/start_survey.html.erb
<p>
In your opinion would it be <i> fair </i> if an individual with Record 1 was <br />
released from prison, while and individual with Record 2 was not? 
</p>

<div class="row" align="left">
            
    <div class="col-sm-6">
        <p>
            <a class="btn btn-info" href= <%="save_comparison/0/#{@record_1.id}/#{@record_2.id}"%> role="button"> Record 1</a>
        </p>
        <p>
            <strong>Crime:</strong>
            <%= @record_1.crime_id %>
        </p>

        <p>
            <strong>Sex:</strong>
            <%= @record_1.sex %>
        </p>


        <p>
            <strong>Age:</strong>
            <%= @record_1.age %>
        </p>

        <p>
            <strong>Race:</strong>
            <%= @record_1.race %>
        </p>

        <p>
            <strong>Juv fel count:</strong>
            <%= @record_1.juv_fel_count %>
        </p>

        <p>
            <strong>Juv misd count:</strong>
            <%= @record_1.juv_misd_count %>
        </p>

        <p>
            <strong>Priors count:</strong>
            <%= @record_1.priors_count %>
        </p>

        <p>
            <strong>C charge degree:</strong>
            <%= @record_1.c_charge_degree %>
        </p>

        <p>
            <strong>Age at first arrest:</strong>
            <%= @record_1.age_at_first_arrest %>
        </p>

        <p>
            <strong>First arrest:</strong>
            <%= @record_1.first_arrest %>
        </p>

        <p>
            <strong>Pending charge:</strong>
            <%= @record_1.pending_charge %>
        </p>

        <p>
            <strong>Prior misdemeanors:</strong>
            <%= @record_1.prior_misdemeanors %>
        </p>

        <p>
            <strong>Prior felonies:</strong>
            <%= @record_1.prior_felonies %>
        </p>

        <p>
            <strong>Prior misdemeanors last year:</strong>
            <%= @record_1.prior_misdemeanors_last_year %>
        </p>

        <p>
            <strong>Prior misdemeanors last two years:</strong>
            <%= @record_1.prior_misdemeanors_last_two_years %>
        </p>

        <p>
            <strong>Violent priors:</strong>
            <%= @record_1.violent_priors %>
        </p>

        <p>
            <strong>Prior incarcerations:</strong>
            <%= @record_1.prior_incarcerations %>
        </p>

        <p>
            <strong>Prior drug convictions:</strong>
            <%= @record_1.prior_drug_convictions %>
        </p>

        <p>
            <strong>Current violent charge:</strong>
            <%= @record_1.current_violent_charge %>
        </p>

        <p>
            <strong>Employment:</strong>
            <%= @record_1.Employment %>
        </p>

        <p>
            <strong>Illegal drug use:</strong>
            <%= @record_1.illegal_drug_use %>
        </p>
    </div>
    
    <div class="col-sm-6">

        <p>
            <a class="btn btn-info" href= <%="save_comparison/1/#{@record_1.id}/#{@record_2.id}"%> role="button"> Record 2</a>
        </p>

        <p>
            <strong>Crime:</strong>
            <%= @record_2.crime_id %>
        </p>

        <p>
            <strong>Sex:</strong>
            <%= @record_2.sex %>
        </p>

        <p>
            <strong>Age:</strong>
            <%= @record_2.age %>
        </p>

        <p>
            <strong>Race:</strong>
            <%= @record_2.race %>
        </p>

        <p>
            <strong>Juv fel count:</strong>
            <%= @record_2.juv_fel_count %>
        </p>

        <p>
            <strong>Juv misd count:</strong>
            <%= @record_2.juv_misd_count %>
        </p>

        <p>
            <strong>Priors count:</strong>
            <%= @record_2.priors_count %>
        </p>

        <p>
            <strong>C charge degree:</strong>
            <%= @record_2.c_charge_degree %>
        </p>

        <p>
            <strong>Age at first arrest:</strong>
            <%= @record_2.age_at_first_arrest %>
        </p>

        <p>
            <strong>First arrest:</strong>
            <%= @record_2.first_arrest %>
        </p>

        <p>
            <strong>Pending charge:</strong>
            <%= @record_2.pending_charge %>
        </p>

        <p>
            <strong>Prior misdemeanors:</strong>
            <%= @record_2.prior_misdemeanors %>
        </p>

        <p>
            <strong>Prior felonies:</strong>
            <%= @record_2.prior_felonies %>
        </p>

        <p>
            <strong>Prior misdemeanors last year:</strong>
            <%= @record_2.prior_misdemeanors_last_year %>
        </p>

        <p>
            <strong>Prior misdemeanors last two years:</strong>
            <%= @record_2.prior_misdemeanors_last_two_years %>
        </p>

        <p>
            <strong>Violent priors:</strong>
            <%= @record_2.violent_priors %>
        </p>

        <p>
            <strong>Prior incarcerations:</strong>
            <%= @record_2.prior_incarcerations %>
        </p>

        <p>
            <strong>Prior drug convictions:</strong>
            <%= @record_2.prior_drug_convictions %>
        </p>

        <p>
            <strong>Current violent charge:</strong>
            <%= @record_2.current_violent_charge %>
        </p>

        <p>
            <strong>Employment:</strong>
            <%= @record_2.Employment %>
        </p>

        <p>
            <strong>Illegal drug use:</strong>
            <%= @record_2.illegal_drug_use %>
        </p>
    </div>
</div>

project/app/views/comparisons/survey_analytics.html.erb
<div class="container">
    <% @pairs.each do |comparison| %>
        <div class="col-md-8">
            <dl>
                <dt>
                    <%= "Record #{comparison.record_1_id} vs. Record #{comparison.record_2_id}" %>
                </dt>
                <% @score_names.each do |score_name| %>
                    <dd class= "percentage percentage-<%=(@scores_dict[String(comparison.record_1.crime_id)][score_name]*100).round%>">
                        <span class="text"> 
                            <%= "#{score_name}_1: #{(@scores_dict[String(comparison.record_1.crime_id)][score_name]*100).round}" %> 
                        </span>
                    </dd>
                    <dd class= "percentage percentage-<%=(@scores_dict[String(comparison.record_2.crime_id)][score_name]*100).round%>">
                        <span class="text"> 
                            <%= "#{score_name}_2: #{(@scores_dict[String(comparison.record_2.crime_id)][score_name]*100).round}" %> 
                        </span>
                    </dd>
                    
                <% end %>
            </dl>
        </div>
    <% end %>
 </div>