project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get root to: 'users#home'
  get 'comparisons/save_comparison/:choice/:record_1_id/:record_2_id', to: 'comparisons#save_comparison'
  post 'comparisons/save_form_params', to: 'comparisons#save_form_params'
  get '/comparisons/start_survey', to: 'comparisons#start_survey'
  get '/comparisons/how_many_pairs', to: 'comparisons#how_many_pairs'
  get '/comparisons/survey_analytics', to: 'comparisons#survey_analytics'
  resources :records 
  resources :users do 
    resources :comparisons
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project/app/models/record.rb
class Record < ApplicationRecord
    has_many :comparisons
end

project/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:crime_id, :name, :first, :last, :compas_screening_date, :sex, :dob, :age, :age_cat, :race, :juv_fel_count, :decile_score, :juv_misd_count, :juv_other_count, :priors_count, :days_b_screening_arrest, :c_jail_in, :c_jail_out, :c_case_number, :c_offense_date, :c_arrest_date, :c_days_from_compas, :c_charge_degree, :c_charge_desc, :is_recid, :r_case_number, :r_charge_degree, :r_offense_date, :r_charge_desc, :r_jail_in, :r_jail_out, :is_violent_recid, :vr_case_number, :vr_charge_degree, :vr_offense_date, :vr_charge_desc, :type_of_assessment, :score_text, :screening_date, :v_type_of_assessment, :v_decile_score, :v_score_text, :v_screening_date, :in_custody, :out_custody, :Start, :end, :event, :two_year_recid, :age_at_first_arrest, :first_arrest, :active_supervision, :pending_charge, :fta_1, :fta_2, :fta_3, :fta_4, :fta_5, :fta_6, :fta_older, :prior_misdemeanors, :prior_felonies, :prior_misdemeanors_last_year, :prior_misdemeanors_last_two_years, :violent_priors, :prior_incarcerations, :prior_drug_convictions, :current_violent_charge, :current_f_dtf, :Employment, :expects_someone, :drug_abuse_history, :illegal_drug_use, :current_residences, :current_residence, :children_spouse_or_parent, :Nyc, :Telephone, :r_days_from_arrest)
    end
end

project/app/helpers/records_helper.rb
module RecordsHelper
end

project/app/views/records/_form.html.erb
<%= form_with(model: record, local: true) do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :crime_id %>
    <%= form.number_field :crime_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :first %>
    <%= form.text_field :first %>
  </div>

  <div class="field">
    <%= form.label :last %>
    <%= form.text_field :last %>
  </div>

  <div class="field">
    <%= form.label :compas_screening_date %>
    <%= form.date_select :compas_screening_date %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :age_cat %>
    <%= form.text_area :age_cat %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_field :race %>
  </div>

  <div class="field">
    <%= form.label :juv_fel_count %>
    <%= form.number_field :juv_fel_count %>
  </div>

  <div class="field">
    <%= form.label :decile_score %>
    <%= form.text_field :decile_score %>
  </div>

  <div class="field">
    <%= form.label :juv_misd_count %>
    <%= form.number_field :juv_misd_count %>
  </div>

  <div class="field">
    <%= form.label :juv_other_count %>
    <%= form.number_field :juv_other_count %>
  </div>

  <div class="field">
    <%= form.label :priors_count %>
    <%= form.number_field :priors_count %>
  </div>

  <div class="field">
    <%= form.label :days_b_screening_arrest %>
    <%= form.number_field :days_b_screening_arrest %>
  </div>

  <div class="field">
    <%= form.label :c_jail_in %>
    <%= form.datetime_select :c_jail_in %>
  </div>

  <div class="field">
    <%= form.label :c_jail_out %>
    <%= form.datetime_select :c_jail_out %>
  </div>

  <div class="field">
    <%= form.label :c_case_number %>
    <%= form.number_field :c_case_number %>
  </div>

  <div class="field">
    <%= form.label :c_offense_date %>
    <%= form.datetime_select :c_offense_date %>
  </div>

  <div class="field">
    <%= form.label :c_arrest_date %>
    <%= form.datetime_select :c_arrest_date %>
  </div>

  <div class="field">
    <%= form.label :c_days_from_compas %>
    <%= form.number_field :c_days_from_compas %>
  </div>

  <div class="field">
    <%= form.label :c_charge_degree %>
    <%= form.text_field :c_charge_degree %>
  </div>

  <div class="field">
    <%= form.label :c_charge_desc %>
    <%= form.text_area :c_charge_desc %>
  </div>

  <div class="field">
    <%= form.label :is_recid %>
    <%= form.number_field :is_recid %>
  </div>

  <div class="field">
    <%= form.label :r_case_number %>
    <%= form.text_field :r_case_number %>
  </div>

  <div class="field">
    <%= form.label :r_charge_degree %>
    <%= form.text_field :r_charge_degree %>
  </div>

  <div class="field">
    <%= form.label :r_offense_date %>
    <%= form.date_select :r_offense_date %>
  </div>

  <div class="field">
    <%= form.label :r_charge_desc %>
    <%= form.text_area :r_charge_desc %>
  </div>

  <div class="field">
    <%= form.label :r_jail_in %>
    <%= form.date_select :r_jail_in %>
  </div>

  <div class="field">
    <%= form.label :r_jail_out %>
    <%= form.date_select :r_jail_out %>
  </div>

  <div class="field">
    <%= form.label :is_violent_recid %>
    <%= form.number_field :is_violent_recid %>
  </div>

  <div class="field">
    <%= form.label :vr_case_number %>
    <%= form.text_field :vr_case_number %>
  </div>

  <div class="field">
    <%= form.label :vr_charge_degree %>
    <%= form.text_field :vr_charge_degree %>
  </div>

  <div class="field">
    <%= form.label :vr_offense_date %>
    <%= form.date_select :vr_offense_date %>
  </div>

  <div class="field">
    <%= form.label :vr_charge_desc %>
    <%= form.text_area :vr_charge_desc %>
  </div>

  <div class="field">
    <%= form.label :type_of_assessment %>
    <%= form.text_area :type_of_assessment %>
  </div>

  <div class="field">
    <%= form.label :score_text %>
    <%= form.text_field :score_text %>
  </div>

  <div class="field">
    <%= form.label :screening_date %>
    <%= form.date_select :screening_date %>
  </div>

  <div class="field">
    <%= form.label :v_type_of_assessment %>
    <%= form.text_area :v_type_of_assessment %>
  </div>

  <div class="field">
    <%= form.label :v_decile_score %>
    <%= form.number_field :v_decile_score %>
  </div>

  <div class="field">
    <%= form.label :v_score_text %>
    <%= form.text_field :v_score_text %>
  </div>

  <div class="field">
    <%= form.label :v_screening_date %>
    <%= form.date_select :v_screening_date %>
  </div>

  <div class="field">
    <%= form.label :in_custody %>
    <%= form.date_select :in_custody %>
  </div>

  <div class="field">
    <%= form.label :out_custody %>
    <%= form.date_select :out_custody %>
  </div>

  <div class="field">
    <%= form.label :Start %>
    <%= form.number_field :Start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.number_field :end %>
  </div>

  <div class="field">
    <%= form.label :event %>
    <%= form.number_field :event %>
  </div>

  <div class="field">
    <%= form.label :two_year_recid %>
    <%= form.number_field :two_year_recid %>
  </div>

  <div class="field">
    <%= form.label :age_at_first_arrest %>
    <%= form.number_field :age_at_first_arrest %>
  </div>

  <div class="field">
    <%= form.label :first_arrest %>
    <%= form.text_field :first_arrest %>
  </div>

  <div class="field">
    <%= form.label :active_supervision %>
    <%= form.number_field :active_supervision %>
  </div>

  <div class="field">
    <%= form.label :pending_charge %>
    <%= form.text_field :pending_charge %>
  </div>

  <div class="field">
    <%= form.label :fta_1 %>
    <%= form.number_field :fta_1 %>
  </div>

  <div class="field">
    <%= form.label :fta_2 %>
    <%= form.number_field :fta_2 %>
  </div>

  <div class="field">
    <%= form.label :fta_3 %>
    <%= form.number_field :fta_3 %>
  </div>

  <div class="field">
    <%= form.label :fta_4 %>
    <%= form.number_field :fta_4 %>
  </div>

  <div class="field">
    <%= form.label :fta_5 %>
    <%= form.number_field :fta_5 %>
  </div>

  <div class="field">
    <%= form.label :fta_6 %>
    <%= form.number_field :fta_6 %>
  </div>

  <div class="field">
    <%= form.label :fta_older %>
    <%= form.number_field :fta_older %>
  </div>

  <div class="field">
    <%= form.label :prior_misdemeanors %>
    <%= form.number_field :prior_misdemeanors %>
  </div>

  <div class="field">
    <%= form.label :prior_felonies %>
    <%= form.number_field :prior_felonies %>
  </div>

  <div class="field">
    <%= form.label :prior_misdemeanors_last_year %>
    <%= form.number_field :prior_misdemeanors_last_year %>
  </div>

  <div class="field">
    <%= form.label :prior_misdemeanors_last_two_years %>
    <%= form.number_field :prior_misdemeanors_last_two_years %>
  </div>

  <div class="field">
    <%= form.label :violent_priors %>
    <%= form.number_field :violent_priors %>
  </div>

  <div class="field">
    <%= form.label :prior_incarcerations %>
    <%= form.number_field :prior_incarcerations %>
  </div>

  <div class="field">
    <%= form.label :prior_drug_convictions %>
    <%= form.number_field :prior_drug_convictions %>
  </div>

  <div class="field">
    <%= form.label :current_violent_charge %>
    <%= form.text_field :current_violent_charge %>
  </div>

  <div class="field">
    <%= form.label :current_f_dtf %>
    <%= form.text_field :current_f_dtf %>
  </div>

  <div class="field">
    <%= form.label :Employment %>
    <%= form.text_field :Employment %>
  </div>

  <div class="field">
    <%= form.label :expects_someone %>
    <%= form.text_field :expects_someone %>
  </div>

  <div class="field">
    <%= form.label :drug_abuse_history %>
    <%= form.text_field :drug_abuse_history %>
  </div>

  <div class="field">
    <%= form.label :illegal_drug_use %>
    <%= form.text_field :illegal_drug_use %>
  </div>

  <div class="field">
    <%= form.label :current_residences %>
    <%= form.text_field :current_residences %>
  </div>

  <div class="field">
    <%= form.label :current_residence %>
    <%= form.text_field :current_residence %>
  </div>

  <div class="field">
    <%= form.label :children_spouse_or_parent %>
    <%= form.text_field :children_spouse_or_parent %>
  </div>

  <div class="field">
    <%= form.label :Nyc %>
    <%= form.text_field :Nyc %>
  </div>

  <div class="field">
    <%= form.label :Telephone %>
    <%= form.text_field :Telephone %>
  </div>

  <div class="field">
    <%= form.label :r_days_from_arrest %>
    <%= form.number_field :r_days_from_arrest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

project/app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th>Crime</th>
      <th>Name</th>
      <th>First</th>
      <th>Last</th>
      <th>Compas screening date</th>
      <th>Sex</th>
      <th>Dob</th>
      <th>Age</th>
      <th>Age cat</th>
      <th>Race</th>
      <th>Juv fel count</th>
      <th>Decile score</th>
      <th>Juv misd count</th>
      <th>Juv other count</th>
      <th>Priors count</th>
      <th>Days b screening arrest</th>
      <th>C jail in</th>
      <th>C jail out</th>
      <th>C case number</th>
      <th>C offense date</th>
      <th>C arrest date</th>
      <th>C days from compas</th>
      <th>C charge degree</th>
      <th>C charge desc</th>
      <th>Is recid</th>
      <th>R case number</th>
      <th>R charge degree</th>
      <th>R offense date</th>
      <th>R charge desc</th>
      <th>R jail in</th>
      <th>R jail out</th>
      <th>Is violent recid</th>
      <th>Vr case number</th>
      <th>Vr charge degree</th>
      <th>Vr offense date</th>
      <th>Vr charge desc</th>
      <th>Type of assessment</th>
      <th>Score text</th>
      <th>Screening date</th>
      <th>V type of assessment</th>
      <th>V decile score</th>
      <th>V score text</th>
      <th>V screening date</th>
      <th>In custody</th>
      <th>Out custody</th>
      <th>Start</th>
      <th>End</th>
      <th>Event</th>
      <th>Two year recid</th>
      <th>Age at first arrest</th>
      <th>First arrest</th>
      <th>Active supervision</th>
      <th>Pending charge</th>
      <th>Fta 1</th>
      <th>Fta 2</th>
      <th>Fta 3</th>
      <th>Fta 4</th>
      <th>Fta 5</th>
      <th>Fta 6</th>
      <th>Fta older</th>
      <th>Prior misdemeanors</th>
      <th>Prior felonies</th>
      <th>Prior misdemeanors last year</th>
      <th>Prior misdemeanors last two years</th>
      <th>Violent priors</th>
      <th>Prior incarcerations</th>
      <th>Prior drug convictions</th>
      <th>Current violent charge</th>
      <th>Current f dtf</th>
      <th>Employment</th>
      <th>Expects someone</th>
      <th>Drug abuse history</th>
      <th>Illegal drug use</th>
      <th>Current residences</th>
      <th>Current residence</th>
      <th>Children spouse or parent</th>
      <th>Nyc</th>
      <th>Telephone</th>
      <th>R days from arrest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.crime_id %></td>
        <td><%= record.name %></td>
        <td><%= record.first %></td>
        <td><%= record.last %></td>
        <td><%= record.compas_screening_date %></td>
        <td><%= record.sex %></td>
        <td><%= record.dob %></td>
        <td><%= record.age %></td>
        <td><%= record.age_cat %></td>
        <td><%= record.race %></td>
        <td><%= record.juv_fel_count %></td>
        <td><%= record.decile_score %></td>
        <td><%= record.juv_misd_count %></td>
        <td><%= record.juv_other_count %></td>
        <td><%= record.priors_count %></td>
        <td><%= record.days_b_screening_arrest %></td>
        <td><%= record.c_jail_in %></td>
        <td><%= record.c_jail_out %></td>
        <td><%= record.c_case_number %></td>
        <td><%= record.c_offense_date %></td>
        <td><%= record.c_arrest_date %></td>
        <td><%= record.c_days_from_compas %></td>
        <td><%= record.c_charge_degree %></td>
        <td><%= record.c_charge_desc %></td>
        <td><%= record.is_recid %></td>
        <td><%= record.r_case_number %></td>
        <td><%= record.r_charge_degree %></td>
        <td><%= record.r_offense_date %></td>
        <td><%= record.r_charge_desc %></td>
        <td><%= record.r_jail_in %></td>
        <td><%= record.r_jail_out %></td>
        <td><%= record.is_violent_recid %></td>
        <td><%= record.vr_case_number %></td>
        <td><%= record.vr_charge_degree %></td>
        <td><%= record.vr_offense_date %></td>
        <td><%= record.vr_charge_desc %></td>
        <td><%= record.type_of_assessment %></td>
        <td><%= record.score_text %></td>
        <td><%= record.screening_date %></td>
        <td><%= record.v_type_of_assessment %></td>
        <td><%= record.v_decile_score %></td>
        <td><%= record.v_score_text %></td>
        <td><%= record.v_screening_date %></td>
        <td><%= record.in_custody %></td>
        <td><%= record.out_custody %></td>
        <td><%= record.Start %></td>
        <td><%= record.end %></td>
        <td><%= record.event %></td>
        <td><%= record.two_year_recid %></td>
        <td><%= record.age_at_first_arrest %></td>
        <td><%= record.first_arrest %></td>
        <td><%= record.active_supervision %></td>
        <td><%= record.pending_charge %></td>
        <td><%= record.fta_1 %></td>
        <td><%= record.fta_2 %></td>
        <td><%= record.fta_3 %></td>
        <td><%= record.fta_4 %></td>
        <td><%= record.fta_5 %></td>
        <td><%= record.fta_6 %></td>
        <td><%= record.fta_older %></td>
        <td><%= record.prior_misdemeanors %></td>
        <td><%= record.prior_felonies %></td>
        <td><%= record.prior_misdemeanors_last_year %></td>
        <td><%= record.prior_misdemeanors_last_two_years %></td>
        <td><%= record.violent_priors %></td>
        <td><%= record.prior_incarcerations %></td>
        <td><%= record.prior_drug_convictions %></td>
        <td><%= record.current_violent_charge %></td>
        <td><%= record.current_f_dtf %></td>
        <td><%= record.Employment %></td>
        <td><%= record.expects_someone %></td>
        <td><%= record.drug_abuse_history %></td>
        <td><%= record.illegal_drug_use %></td>
        <td><%= record.current_residences %></td>
        <td><%= record.current_residence %></td>
        <td><%= record.children_spouse_or_parent %></td>
        <td><%= record.Nyc %></td>
        <td><%= record.Telephone %></td>
        <td><%= record.r_days_from_arrest %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

project/app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

project/app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Crime:</strong>
  <%= @record.crime_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @record.name %>
</p>

<p>
  <strong>First:</strong>
  <%= @record.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @record.last %>
</p>

<p>
  <strong>Compas screening date:</strong>
  <%= @record.compas_screening_date %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @record.sex %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @record.dob %>
</p>

<p>
  <strong>Age:</strong>
  <%= @record.age %>
</p>

<p>
  <strong>Age cat:</strong>
  <%= @record.age_cat %>
</p>

<p>
  <strong>Race:</strong>
  <%= @record.race %>
</p>

<p>
  <strong>Juv fel count:</strong>
  <%= @record.juv_fel_count %>
</p>

<p>
  <strong>Decile score:</strong>
  <%= @record.decile_score %>
</p>

<p>
  <strong>Juv misd count:</strong>
  <%= @record.juv_misd_count %>
</p>

<p>
  <strong>Juv other count:</strong>
  <%= @record.juv_other_count %>
</p>

<p>
  <strong>Priors count:</strong>
  <%= @record.priors_count %>
</p>

<p>
  <strong>Days b screening arrest:</strong>
  <%= @record.days_b_screening_arrest %>
</p>

<p>
  <strong>C jail in:</strong>
  <%= @record.c_jail_in %>
</p>

<p>
  <strong>C jail out:</strong>
  <%= @record.c_jail_out %>
</p>

<p>
  <strong>C case number:</strong>
  <%= @record.c_case_number %>
</p>

<p>
  <strong>C offense date:</strong>
  <%= @record.c_offense_date %>
</p>

<p>
  <strong>C arrest date:</strong>
  <%= @record.c_arrest_date %>
</p>

<p>
  <strong>C days from compas:</strong>
  <%= @record.c_days_from_compas %>
</p>

<p>
  <strong>C charge degree:</strong>
  <%= @record.c_charge_degree %>
</p>

<p>
  <strong>C charge desc:</strong>
  <%= @record.c_charge_desc %>
</p>

<p>
  <strong>Is recid:</strong>
  <%= @record.is_recid %>
</p>

<p>
  <strong>R case number:</strong>
  <%= @record.r_case_number %>
</p>

<p>
  <strong>R charge degree:</strong>
  <%= @record.r_charge_degree %>
</p>

<p>
  <strong>R offense date:</strong>
  <%= @record.r_offense_date %>
</p>

<p>
  <strong>R charge desc:</strong>
  <%= @record.r_charge_desc %>
</p>

<p>
  <strong>R jail in:</strong>
  <%= @record.r_jail_in %>
</p>

<p>
  <strong>R jail out:</strong>
  <%= @record.r_jail_out %>
</p>

<p>
  <strong>Is violent recid:</strong>
  <%= @record.is_violent_recid %>
</p>

<p>
  <strong>Vr case number:</strong>
  <%= @record.vr_case_number %>
</p>

<p>
  <strong>Vr charge degree:</strong>
  <%= @record.vr_charge_degree %>
</p>

<p>
  <strong>Vr offense date:</strong>
  <%= @record.vr_offense_date %>
</p>

<p>
  <strong>Vr charge desc:</strong>
  <%= @record.vr_charge_desc %>
</p>

<p>
  <strong>Type of assessment:</strong>
  <%= @record.type_of_assessment %>
</p>

<p>
  <strong>Score text:</strong>
  <%= @record.score_text %>
</p>

<p>
  <strong>Screening date:</strong>
  <%= @record.screening_date %>
</p>

<p>
  <strong>V type of assessment:</strong>
  <%= @record.v_type_of_assessment %>
</p>

<p>
  <strong>V decile score:</strong>
  <%= @record.v_decile_score %>
</p>

<p>
  <strong>V score text:</strong>
  <%= @record.v_score_text %>
</p>

<p>
  <strong>V screening date:</strong>
  <%= @record.v_screening_date %>
</p>

<p>
  <strong>In custody:</strong>
  <%= @record.in_custody %>
</p>

<p>
  <strong>Out custody:</strong>
  <%= @record.out_custody %>
</p>

<p>
  <strong>Start:</strong>
  <%= @record.Start %>
</p>

<p>
  <strong>End:</strong>
  <%= @record.end %>
</p>

<p>
  <strong>Event:</strong>
  <%= @record.event %>
</p>

<p>
  <strong>Two year recid:</strong>
  <%= @record.two_year_recid %>
</p>

<p>
  <strong>Age at first arrest:</strong>
  <%= @record.age_at_first_arrest %>
</p>

<p>
  <strong>First arrest:</strong>
  <%= @record.first_arrest %>
</p>

<p>
  <strong>Active supervision:</strong>
  <%= @record.active_supervision %>
</p>

<p>
  <strong>Pending charge:</strong>
  <%= @record.pending_charge %>
</p>

<p>
  <strong>Fta 1:</strong>
  <%= @record.fta_1 %>
</p>

<p>
  <strong>Fta 2:</strong>
  <%= @record.fta_2 %>
</p>

<p>
  <strong>Fta 3:</strong>
  <%= @record.fta_3 %>
</p>

<p>
  <strong>Fta 4:</strong>
  <%= @record.fta_4 %>
</p>

<p>
  <strong>Fta 5:</strong>
  <%= @record.fta_5 %>
</p>

<p>
  <strong>Fta 6:</strong>
  <%= @record.fta_6 %>
</p>

<p>
  <strong>Fta older:</strong>
  <%= @record.fta_older %>
</p>

<p>
  <strong>Prior misdemeanors:</strong>
  <%= @record.prior_misdemeanors %>
</p>

<p>
  <strong>Prior felonies:</strong>
  <%= @record.prior_felonies %>
</p>

<p>
  <strong>Prior misdemeanors last year:</strong>
  <%= @record.prior_misdemeanors_last_year %>
</p>

<p>
  <strong>Prior misdemeanors last two years:</strong>
  <%= @record.prior_misdemeanors_last_two_years %>
</p>

<p>
  <strong>Violent priors:</strong>
  <%= @record.violent_priors %>
</p>

<p>
  <strong>Prior incarcerations:</strong>
  <%= @record.prior_incarcerations %>
</p>

<p>
  <strong>Prior drug convictions:</strong>
  <%= @record.prior_drug_convictions %>
</p>

<p>
  <strong>Current violent charge:</strong>
  <%= @record.current_violent_charge %>
</p>

<p>
  <strong>Current f dtf:</strong>
  <%= @record.current_f_dtf %>
</p>

<p>
  <strong>Employment:</strong>
  <%= @record.Employment %>
</p>

<p>
  <strong>Expects someone:</strong>
  <%= @record.expects_someone %>
</p>

<p>
  <strong>Drug abuse history:</strong>
  <%= @record.drug_abuse_history %>
</p>

<p>
  <strong>Illegal drug use:</strong>
  <%= @record.illegal_drug_use %>
</p>

<p>
  <strong>Current residences:</strong>
  <%= @record.current_residences %>
</p>

<p>
  <strong>Current residence:</strong>
  <%= @record.current_residence %>
</p>

<p>
  <strong>Children spouse or parent:</strong>
  <%= @record.children_spouse_or_parent %>
</p>

<p>
  <strong>Nyc:</strong>
  <%= @record.Nyc %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @record.Telephone %>
</p>

<p>
  <strong>R days from arrest:</strong>
  <%= @record.r_days_from_arrest %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>